"""add coverage_elevations

Revision ID: 83bb5a1a5395
Revises: b4e400133686
Create Date: 2026-09-04 16:19:44.722038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83bb5a1a5395'
down_revision: Union[str, Sequence[str], None] = 'b4e400133686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coverage_elevations',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('elevated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_coverage_elevations_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_elevations'))
    )
    op.create_index(op.f('ix_coverage_elevations_account_id'), 'coverage_elevations', ['account_id'], unique=False)
    op.create_index(op.f('ix_coverage_elevations_trigger'), 'coverage_elevations', ['trigger'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coverage_elevations_trigger'), table_name='coverage_elevations')
    op.drop_index(op.f('ix_coverage_elevations_account_id'), table_name='coverage_elevations')
    op.drop_table('coverage_elevations')
    # ### end Alembic commands ###
