"""add stakeholder reference_willing

Revision ID: b4e400133686
Revises: d9cb69cc7480
Create Date: 2026-09-01 22:12:56.009416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e400133686'
down_revision: Union[str, Sequence[str], None] = 'd9cb69cc7480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted: a server_default is required so existing rows backfill
    # instead of violating NOT NULL — autogenerate doesn't add one since
    # the Python-side model default (default=False) only applies to new
    # INSERTs, not this ALTER TABLE against already-populated data.
    op.add_column(
        'stakeholders',
        sa.Column('reference_willing', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stakeholders', 'reference_willing')
    # ### end Alembic commands ###
