"""initial canonical schema

Revision ID: d9cb69cc7480
Revises: 
Create Date: 2026-09-01 20:58:44.941488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9cb69cc7480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_identities',
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_identities'))
    )
    op.create_index(op.f('ix_account_identities_external_id'), 'account_identities', ['external_id'], unique=True)
    op.create_table('account_plans',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('stated_objective', sa.Text(), nullable=True),
    sa.Column('how_measured', sa.Text(), nullable=True),
    sa.Column('baseline', sa.Text(), nullable=True),
    sa.Column('potential_basis', sa.Text(), nullable=True),
    sa.Column('top_risk', sa.Text(), nullable=True),
    sa.Column('top_opportunity', sa.Text(), nullable=True),
    sa.Column('last_refreshed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_account_plans_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_plans'))
    )
    op.create_index(op.f('ix_account_plans_account_id'), 'account_plans', ['account_id'], unique=False)
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contract_start', sa.Date(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('commercial_model', sa.Enum('ad_hoc', 'committed', name='commercial_model'), nullable=False),
    sa.Column('committed_volume', sa.Integer(), nullable=True),
    sa.Column('commitment_end', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('tier', sa.Enum('T1', 'T2', 'T3', 'T4', name='tier'), nullable=False),
    sa.Column('quadrant', sa.Enum('invest', 'protect', 'maintain', 'qualify', name='quadrant'), nullable=False),
    sa.Column('potential_departments', sa.Integer(), nullable=True),
    sa.Column('potential_creators_per_dept', sa.Integer(), nullable=True),
    sa.Column('potential_campaigns_per_creator', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_accounts_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_account_id'), 'accounts', ['account_id'], unique=False)
    op.create_index('ux_accounts_current', 'accounts', ['account_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('billing_periods',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('billable_campaign_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_billing_periods_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_periods')),
    sa.UniqueConstraint('account_id', 'period', name='uq_billing_periods_account_period')
    )
    op.create_index(op.f('ix_billing_periods_account_id'), 'billing_periods', ['account_id'], unique=False)
    op.create_table('departments',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_campaign_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_departments_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments'))
    )
    op.create_index(op.f('ix_departments_account_id'), 'departments', ['account_id'], unique=False)
    op.create_index(op.f('ix_departments_external_id'), 'departments', ['external_id'], unique=True)
    op.create_table('feedback_items',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('verbatim', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('routed_to', sa.String(), nullable=True),
    sa.Column('linked_ticket', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_feedback_items_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback_items'))
    )
    op.create_index(op.f('ix_feedback_items_account_id'), 'feedback_items', ['account_id'], unique=False)
    op.create_table('health_scores',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('volume_trajectory_score', sa.Float(), nullable=True),
    sa.Column('breadth_score', sa.Float(), nullable=True),
    sa.Column('value_realisation_score', sa.Float(), nullable=True),
    sa.Column('campaign_quality_score', sa.Float(), nullable=True),
    sa.Column('relationship_coverage_score', sa.Float(), nullable=True),
    sa.Column('sentiment_friction_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('band', sa.Enum('healthy', 'watch', 'at_risk', 'critical', name='health_band'), nullable=True),
    sa.Column('applied_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('null_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_health_scores_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_scores'))
    )
    op.create_index(op.f('ix_health_scores_account_id'), 'health_scores', ['account_id'], unique=False)
    op.create_table('play_runs',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('play', sa.Enum('onboarding', 'decay', 'renewal', 'expansion', name='play_type'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('cause_classification', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_play_runs_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_play_runs'))
    )
    op.create_index(op.f('ix_play_runs_account_id'), 'play_runs', ['account_id'], unique=False)
    op.create_table('product_errors',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_product_errors_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_errors'))
    )
    op.create_index(op.f('ix_product_errors_account_id'), 'product_errors', ['account_id'], unique=False)
    op.create_table('signals',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('T1', 'T2', 'T3', name='signal_severity'), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_signals_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_account_id'), 'signals', ['account_id'], unique=False)
    op.create_index(op.f('ix_signals_type'), 'signals', ['type'], unique=False)
    op.create_table('stakeholders',
    sa.Column('stakeholder_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('economic_buyer', 'exec_sponsor', 'champion', 'creator', 'blocker', name='stakeholder_type'), nullable=False),
    sa.Column('relationship_strength', sa.Enum('strong', 'neutral', 'weak', 'unknown', name='relationship_strength'), nullable=False),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_stakeholders_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stakeholders'))
    )
    op.create_index(op.f('ix_stakeholders_account_id'), 'stakeholders', ['account_id'], unique=False)
    op.create_index(op.f('ix_stakeholders_stakeholder_id'), 'stakeholders', ['stakeholder_id'], unique=False)
    op.create_index('ux_stakeholders_current', 'stakeholders', ['stakeholder_id'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('value_docs',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_value_docs_account_id_account_identities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_value_docs'))
    )
    op.create_index(op.f('ix_value_docs_account_id'), 'value_docs', ['account_id'], unique=False)
    op.create_table('actions',
    sa.Column('play_run_id', sa.UUID(), nullable=True),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('autonomy_level', sa.Enum('auto', 'draft', 'human_writes', 'never', name='autonomy_level'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'edited', 'rejected', 'executed', name='action_status'), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('rejection_reason_category', sa.Enum('wrong_cause', 'wrong_tone', 'wrong_recipient', 'factually_incorrect', 'volume_pushing', 'premature', 'other', name='rejection_reason_category'), nullable=True),
    sa.Column('rejection_reason_detail', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status != 'rejected' OR rejection_reason_category IS NOT NULL", name=op.f('ck_actions_rejection_reason_required')),
    sa.ForeignKeyConstraint(['play_run_id'], ['play_runs.id'], name=op.f('fk_actions_play_run_id_play_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actions'))
    )
    op.create_index(op.f('ix_actions_play_run_id'), 'actions', ['play_run_id'], unique=False)
    op.create_table('users',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_users_account_id_account_identities')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('campaigns',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_campaigns_account_id_account_identities')),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], name=op.f('fk_campaigns_creator_user_id_users')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_campaigns_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_index(op.f('ix_campaigns_creator_user_id'), 'campaigns', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_department_id'), 'campaigns', ['department_id'], unique=False)
    op.create_index(op.f('ix_campaigns_external_id'), 'campaigns', ['external_id'], unique=True)
    op.create_table('user_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('deactivation', 'invitation_sent', 'invitation_accepted', name='user_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account_identities.id'], name=op.f('fk_user_events_account_id_account_identities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_events_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_events'))
    )
    op.create_index(op.f('ix_user_events_account_id'), 'user_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_events_user_id'), 'user_events', ['user_id'], unique=False)
    op.create_table('campaign_outcomes',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('response_rate', sa.Float(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_outcomes_campaign_id_campaigns')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_outcomes'))
    )
    op.create_index(op.f('ix_campaign_outcomes_campaign_id'), 'campaign_outcomes', ['campaign_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_outcomes_campaign_id'), table_name='campaign_outcomes')
    op.drop_table('campaign_outcomes')
    op.drop_index(op.f('ix_user_events_user_id'), table_name='user_events')
    op.drop_index(op.f('ix_user_events_account_id'), table_name='user_events')
    op.drop_table('user_events')
    op.drop_index(op.f('ix_campaigns_external_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_department_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_creator_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_actions_play_run_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_value_docs_account_id'), table_name='value_docs')
    op.drop_table('value_docs')
    op.drop_index('ux_stakeholders_current', table_name='stakeholders', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index(op.f('ix_stakeholders_stakeholder_id'), table_name='stakeholders')
    op.drop_index(op.f('ix_stakeholders_account_id'), table_name='stakeholders')
    op.drop_table('stakeholders')
    op.drop_index(op.f('ix_signals_type'), table_name='signals')
    op.drop_index(op.f('ix_signals_account_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_product_errors_account_id'), table_name='product_errors')
    op.drop_table('product_errors')
    op.drop_index(op.f('ix_play_runs_account_id'), table_name='play_runs')
    op.drop_table('play_runs')
    op.drop_index(op.f('ix_health_scores_account_id'), table_name='health_scores')
    op.drop_table('health_scores')
    op.drop_index(op.f('ix_feedback_items_account_id'), table_name='feedback_items')
    op.drop_table('feedback_items')
    op.drop_index(op.f('ix_departments_external_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_account_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_billing_periods_account_id'), table_name='billing_periods')
    op.drop_table('billing_periods')
    op.drop_index('ux_accounts_current', table_name='accounts', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index(op.f('ix_accounts_account_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_account_plans_account_id'), table_name='account_plans')
    op.drop_table('account_plans')
    op.drop_index(op.f('ix_account_identities_external_id'), table_name='account_identities')
    op.drop_table('account_identities')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for Postgres native enums on
    # downgrade — they're created implicitly by the first CREATE TABLE
    # that uses them and orphaned otherwise. Drop them explicitly so
    # downgrade -> upgrade round-trips cleanly instead of erroring on
    # "type already exists" the second time upgrade runs.
    for enum_name in (
        'commercial_model', 'tier', 'quadrant', 'user_event_type',
        'stakeholder_type', 'relationship_strength', 'health_band',
        'signal_severity', 'play_type', 'autonomy_level', 'action_status',
        'rejection_reason_category',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
