"""add signal reason and evidence

Revision ID: dad9568f048c
Revises: 83bb5a1a5395
Create Date: 2026-09-04 17:15:35.378554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad9568f048c'
down_revision: Union[str, Sequence[str], None] = '83bb5a1a5395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adjusted: server_default backfills existing rows (created before
    # this column existed) instead of violating NOT NULL — same pattern
    # as the reference_willing migration.
    op.add_column('signals', sa.Column('reason', sa.Text(), nullable=False, server_default='(reason not recorded — signal predates this column)'))
    op.add_column('signals', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'evidence')
    op.drop_column('signals', 'reason')
    # ### end Alembic commands ###
